CREATE DATABASE CarRentalDB;
GO

USE CarRentalDB;
GO

CREATE TABLE Branch (
    BranchID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);
GO

CREATE TABLE CarType (
    TypeID INT IDENTITY(1,1) PRIMARY KEY,
    TypeName VARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE Customer (
    CustomerID INT IDENTITY(1,1) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Tel VARCHAR(20) UNIQUE,
    Password NVARCHAR(100) NOT NULL DEFAULT '1234',
    IsAdmin BIT NOT NULL DEFAULT 0
);
GO

CREATE TABLE Car (
    CarID INT IDENTITY(1,1) PRIMARY KEY,
    LicensePlate VARCHAR(20) NOT NULL UNIQUE,
    Model VARCHAR(100) NOT NULL,
    TypeID INT NOT NULL FOREIGN KEY REFERENCES CarType(TypeID),
    BranchID INT NOT NULL FOREIGN KEY REFERENCES Branch(BranchID),
    Status VARCHAR(20) NOT NULL DEFAULT 'Available',
    Gear VARCHAR(10) DEFAULT 'Auto' NOT NULL,
    EngineCC INT DEFAULT 1500 NOT NULL,
    DailyRate DECIMAL(10, 2) NOT NULL DEFAULT 0
);
GO

CREATE TABLE Rental (
    RentalID INT IDENTITY(1,1) PRIMARY KEY,
    CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
    CarID INT NOT NULL FOREIGN KEY REFERENCES Car(CarID),
    StartDate DATE NOT NULL,
    ExpectedReturnDate DATE NOT NULL,
    ActualReturnDate DATE NULL,
    RentalBranchID INT NOT NULL FOREIGN KEY REFERENCES Branch(BranchID),
    TotalFee DECIMAL(10, 2) NULL,
    LateFee DECIMAL(10, 2) NULL
);
GO